[package]
name = "city_generator"
version = "0.1.0"
authors = ["HeoliaJdR <admin@heolia.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
